# Generated by Django 5.0.7 on 2024-10-09 02:06

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_userprofile_photo_alter_leaveapplication_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='employee',
            field=models.CharField(max_length=20, verbose_name=django.contrib.auth.models.User),
        ),
    ]
