# Generated by Django 5.0.7 on 2024-10-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_leaveapplication_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='employee',
            field=models.CharField(max_length=20),
        ),
    ]
